import * as fs from "fs";
import { execSync } from "child_process";
import type { FeatureIndex } from "./types.js";

interface FeatureChange {
  featureId: string;
  changes: {
    usage?: {
      old: number;
      new: number;
      delta: number;
    };
    support?: Array<{
      browser: string;
      old: "y" | "a" | "n" | "p";
      new: "y" | "a" | "n" | "p";
    }>;
    baseline?: {
      old: "high" | "low" | false;
      new: "high" | "low" | false;
    };
  };
}

interface ChangeReport {
  timestamp: string;
  previousCommit: string;
  currentCommit: string;
  totalChanges: number;
  changes: FeatureChange[];
}

interface ChangeHistory {
  lastUpdated: string;
  entries: ChangeReport[];
}

// =================================================================
// MAIN
// =================================================================

async function main(): Promise<void> {
  try {
    // Load current index from disk (freshly generated by normalize-data)
    const currentIndex: FeatureIndex[] = JSON.parse(
      fs.readFileSync("./public/data/index.json", "utf8")
    );
    console.log(`  ✅ Loaded ${currentIndex.length} features from disk`);

    // Load previous index from git HEAD (the last committed version)
    // Note: detect-changes runs BEFORE the commit step, so HEAD is still the previous commit
    let previousIndex: FeatureIndex[];
    let previousCommit: string;

    try {
      previousCommit = execSync("git rev-parse HEAD", {
        encoding: "utf8",
      }).trim();

      const previousFile = execSync("git show HEAD:public/data/index.json", {
        encoding: "utf8",
        maxBuffer: 10 * 1024 * 1024, // 10MB buffer for large files
      });

      previousIndex = JSON.parse(previousFile);
      console.log(
        `  ✅ Loaded ${previousIndex.length} features from HEAD (${previousCommit.substring(0, 7)})`
      );
    } catch (error) {
      console.log(
        "  ⚠️  No previous commit found (first run?). Skipping change detection."
      );
      const emptyReport: ChangeReport = {
        timestamp: new Date().toISOString(),
        previousCommit: "none",
        currentCommit: "pending",
        totalChanges: 0,
        changes: [],
      };
      writeChangeReport(emptyReport);
      return;
    }

    // Detect changes
    console.log("\n🔍 Detecting changes...");
    const changes = detectChanges(currentIndex, previousIndex);
    console.log(`  ✅ Found ${changes.length} changed features`);

    // Generate report
    const report: ChangeReport = {
      timestamp: new Date().toISOString(),
      previousCommit,
      currentCommit: "pending",
      totalChanges: changes.length,
      changes,
    };

    // Write report
    writeChangeReport(report);

    // Summary
    console.log(`Total changes: ${changes.length}`);

    if (changes.length > 0) {
      console.log("\nChanged features:");
      changes.slice(0, 10).forEach((change) => {
        console.log(`  - ${change.featureId}`);
      });
      if (changes.length > 10) {
        console.log(`  ... and ${changes.length - 10} more`);
      }
    }
  } catch (error) {
    console.error("\n❌ Fatal error during change detection:");
    console.error(error);
    process.exit(1);
  }
}

// ============================================================================
// CHANGE DETECTION
// ============================================================================

function detectChanges(
  current: FeatureIndex[],
  previous: FeatureIndex[]
): FeatureChange[] {
  const changes: FeatureChange[] = [];
  const prevMap = new Map(previous.map((f) => [f.id, f]));

  for (const currFeature of current) {
    const prevFeature = prevMap.get(currFeature.id);

    if (!prevFeature) {
      // New feature - skip
      continue;
    }

    const featureChanges: FeatureChange["changes"] = {};

    // Check usage change (>1% threshold)
    const usageDelta = Math.abs(currFeature.usage - prevFeature.usage);
    if (usageDelta > 1.0) {
      featureChanges.usage = {
        old: prevFeature.usage,
        new: currFeature.usage,
        delta: currFeature.usage - prevFeature.usage,
      };
    }

    // Check browser support changes
    const supportChanges: Array<{
      browser: string;
      old: "y" | "a" | "n" | "p";
      new: "y" | "a" | "n" | "p";
    }> = [];

    for (const [browser, newStatus] of Object.entries(currFeature.support)) {
      const oldStatus = prevFeature.support[browser];
      if (newStatus !== oldStatus) {
        supportChanges.push({
          browser,
          old: oldStatus,
          new: newStatus,
        });
      }
    }

    if (supportChanges.length > 0) {
      featureChanges.support = supportChanges;
    }

    // Check baseline status change
    if (currFeature.baseline !== prevFeature.baseline) {
      featureChanges.baseline = {
        old: prevFeature.baseline,
        new: currFeature.baseline,
      };
    }

    // If any changes detected, add to list
    if (Object.keys(featureChanges).length > 0) {
      changes.push({
        featureId: currFeature.id,
        changes: featureChanges,
      });
    }
  }

  return changes;
}

// ============================================================================
// REPORT WRITING
// ============================================================================

function writeChangeReport(report: ChangeReport): void {
  // 1. Update persistent change history (committed to repo)
  const historyPath = "./public/data/change-history.json";

  let history: ChangeHistory;

  if (fs.existsSync(historyPath)) {
    const existingData = fs.readFileSync(historyPath, "utf8").trim();

    if (existingData.length > 0) {
      history = JSON.parse(existingData);
    } else {
      history = { lastUpdated: "", entries: [] };
    }
  } else {
    history = { lastUpdated: "", entries: [] };
  }

  history.entries.unshift(report);
  history.lastUpdated = report.timestamp;

  fs.writeFileSync(historyPath, JSON.stringify(history, null, 2), "utf8");
  console.log(`\n💾 Change history updated: ${historyPath} (${history.entries.length} total entries)`);

  // 2. Write ephemeral change report for CI artifact upload
  const reportDir = "./data";
  const reportPath = `${reportDir}/change-report.json`;

  if (!fs.existsSync(reportDir)) {
    fs.mkdirSync(reportDir, { recursive: true });
  }

  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2), "utf8");
  console.log(`📄 Change report written: ${reportPath}`);
}

// ============================================================================
// RUN
// ============================================================================

main().catch((error) => {
  console.error("\n❌ Fatal error:", error);
  process.exit(1);
});